force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>Movie-{0000}</displayFormat>
        <label>Movie Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Adventure</fullName>
            </value>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie__c/fields/ReleaseDate__c.field-meta.xml
<CustomField>
    <fullName>ReleaseDate__c</fullName>
    <label>Release date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MovieController.cls
public with sharing class MovieController {

    @AuraEnabled
    public static List<Movie__c> getMovieList(String searchKey) {
        searchKey = '%'+searchKey+'%';
        return [
            SELECT Id, Name__c, Category__c,Description__c,ReleaseDate__c,Image__c
            FROM Movie__c
            WHERE Name__c LIKE :searchKey
            WITH SECURITY_ENFORCED
            LIMIT 10
        ];
    }
}