force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>Movie-{0000}</displayFormat>
        <label>Movie Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/IsReleased__c.field-meta.xml
<CustomField>
    <fullName>IsReleased__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Released</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/ReleaseDate__c.field-meta.xml
<CustomField>
    <fullName>ReleaseDate__c</fullName>
    <label>Release date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MyBatchClass.cls
global class MyBatchClass implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, IsReleased__c FROM Movie__c WHERE ReleaseDate__c <= TODAY AND IsReleased__c = false';
        return Database.getQueryLocator(query);
    }
     
    global void execute(Database.BatchableContext BC, List<Movie__c> movies) {
        
        // process each batch of records default size is 200
        for(Movie__c m : movies) {        
           m.IsReleased__c = true;
        }
        try {
            update movies;
         
        } catch(Exception e) {
            System.debug(e);
        }
         
    }   
     
    global void finish(Database.BatchableContext BC) {
        // execute any post-processing operations like sending email
    }
      
}