force-app/main/default/objects/Actor__c/Actor__c.object-meta.xml
<CustomObject>
    <label>Actor</label>
    <nameField>
        <displayFormat>Actor-{0000}</displayFormat>
        <label>Actor identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Actor__c/fields/NumberOfmovies__c.field-meta.xml
<CustomField>
    <fullName>NumberOfmovies__c</fullName>
    <label>Number of movies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>Movie-{0000}</displayFormat>
        <label>Movie Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MovieActor__c/MovieActor__c.object-meta.xml
<CustomObject>
    <label>MovieActor</label>
    <nameField>
        <label>MovieActor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MovieActors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MovieActor__c/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Actor</label>
    <referenceTo>Actor__c</referenceTo>
    <relationshipLabel>MovieActors</relationshipLabel>
    <relationshipName>MovieActors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MovieActor__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>MovieActors</relationshipLabel>
    <relationshipName>MovieActors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MovieActorTriggerHandler_Test.cls
@isTest
public class MovieActorTriggerHandler_Test {

    @isTest
    public static void updateActorNumberOfMovies_Test(){
        List<Movie__c> movies = (List<Movie__c> ) TestDataFactory.createSObjectList('Movie__c',40);
        List<Actor__c> actors = (List<Actor__c> ) TestDataFactory.createSObjectList('Actor__c',10);
        List<MovieActor__c> acts = new List<MovieActor__c>();
        for(Movie__c movie : movies){
            MovieActor__c a = new MovieActor__c(Actor__c = actors[0].Id, Movie__c = movie.Id);
            acts.add(a);
        }
        Test.startTest();
            insert acts;

            acts = [SELECT id ,Actor__c FROM MovieActor__c];
            for(integer i=0;i<10;i++){
                acts[i].Actor__c = actors[i].Id;
            }
            update acts;
		Test.stopTest();
            
        List<Actor__c> actorsResult = [SELECT id , NumberOfmovies__c FROM Actor__c];
		System.assertEquals(actorsResult[1].NumberOfmovies__c,1);
    }
}